# redsentinel/reporter.py
from jinja2 import Template
from redsentinel.utils import now_iso
import json
import os


HTML_TMPL = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>RedSentinel Report — {{ target }}</title>
<style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 20px; background: #1e1e1e; color: #d4d4d4; }
    h1 { color: #ff0000; border-bottom: 2px solid #ff0000; padding-bottom: 10px; }
    h2 { color: #ff4444; margin-top: 30px; }
    .header { background: #2d2d30; padding: 20px; border-radius: 5px; margin-bottom: 20px; }
    .section { background: #252526; padding: 15px; border-radius: 5px; margin: 15px 0; }
    ul { list-style: none; padding-left: 0; }
    li { padding: 5px 0; border-bottom: 1px solid #3e3e42; }
    li:before { content: "• "; color: #ff0000; font-weight: bold; }
    table { width: 100%; border-collapse: collapse; margin: 10px 0; }
    th, td { padding: 10px; text-align: left; border-bottom: 1px solid #3e3e42; }
    th { background: #007acc; color: white; }
    tr:hover { background: #2d2d30; }
    pre { background: #1e1e1e; padding: 10px; border-radius: 5px; overflow-x: auto; }
    .status-200 { color: #4ec9b0; }
    .status-300 { color: #dcdcaa; }
    .status-400 { color: #f48771; }
    .status-500 { color: #f48771; }
</style>
</head>
<body>
    <div class="header">
        <h1>🔴 RedSentinel Security Report</h1>
        <p><strong>Target:</strong> {{ target }}</p>
        <p><strong>Generated:</strong> {{ generated }}</p>
    </div>

    <h2>📊 Summary</h2>
    <div class="section">
        <ul>
            <li>Subdomains found: <strong>{{ subdomains|length }}</strong></li>
            <li>Open ports: <strong>{{ ports|length }}</strong></li>
            <li>HTTP checks: <strong>{{ http|length }}</strong></li>
        </ul>
    </div>

    <h2>🌐 Subdomains ({{ subdomains|length }})</h2>
    <div class="section">
        <ul>
        {% for s in subdomains[:100] %}
            <li>{{ s }}</li>
        {% endfor %}
        {% if subdomains|length > 100 %}
            <li><em>... and {{ subdomains|length - 100 }} more</em></li>
        {% endif %}
        </ul>
    </div>

    <h2>🔌 Open Ports</h2>
    <div class="section">
        <table>
            <tr><th>Port</th><th>Status</th></tr>
            {% for p,o in ports.items() %}
            <tr>
                <td>{{ p }}</td>
                <td class="status-{% if o %}200{% else %}400{% endif %}">
                    {{ "🟢 Open" if o else "🔴 Closed" }}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <h2>🌍 HTTP Checks</h2>
    <div class="section">
        {% for h in http %}
        <div style="margin-bottom: 20px;">
            <h3>{{ h.url }}</h3>
            <p><strong>Status:</strong> <span class="status-{{ h.status if h.status else '400' }}">
                {{ h.status if h.status is defined else h.error }}
            </span></p>
            {% if h.headers %}
            <details>
                <summary>Headers</summary>
                <pre>{{ h.headers }}</pre>
            </details>
            {% endif %}
        </div>
        {% endfor %}
    </div>

    <div class="header">
        <p><em>Report generated by RedSentinel - Cybersecurity & Pentest Toolkit</em></p>
        <p style="color: #808080; font-size: 12px;">⚠️ For authorized use only</p>
    </div>
</body>
</html>
"""


def render_report(target, subdomains=None, ports=None, http_checks=None):
    """Render HTML report"""
    tpl = Template(HTML_TMPL)
    return tpl.render(
        target=target, 
        subdomains=subdomains or [], 
        ports=ports or {}, 
        http=http_checks or [], 
        generated=now_iso()
    )


def render_json_report(target, data):
    """Render JSON report"""
    report = {
        "target": target,
        "generated": now_iso(),
        "data": data
    }
    return json.dumps(report, indent=2)


def render_markdown_report(target, subdomains=None, ports=None, http_checks=None):
    """Render Markdown report"""
    md = f"""# RedSentinel Security Report

**Target:** {target}  
**Generated:** {now_iso()}

## Summary

- Subdomains found: **{len(subdomains) if subdomains else 0}**
- Open ports: **{len(ports) if ports else 0}**
- HTTP checks: **{len(http_checks) if http_checks else 0}**

## Subdomains

"""
    if subdomains:
        for sub in subdomains[:100]:
            md += f"- {sub}\n"
        if len(subdomains) > 100:
            md += f"- ... and {len(subdomains) - 100} more\n"
    
    md += "\n## Open Ports\n\n"
    if ports:
        md += "| Port | Status |\n"
        md += "|------|--------|\n"
        for p, o in ports.items():
            md += f"| {p} | {'🟢 Open' if o else '🔴 Closed'} |\n"
    
    md += "\n## HTTP Checks\n\n"
    if http_checks:
        for h in http_checks:
            md += f"### {h.get('url', 'Unknown')}\n\n"
            md += f"**Status:** {h.get('status', h.get('error', 'Unknown'))}\n\n"
            if h.get('headers'):
                md += f"```\n{h['headers']}\n```\n\n"
    
    md += f"\n---\n\n*Report generated by RedSentinel*\n"
    return md


def export_report(target, data, format="html", output_dir="."):
    """Export report to file"""
    if format == "html":
        content = render_report(
            target, 
            data.get("subdomains"),
            data.get("ports"),
            data.get("http_checks")
        )
        ext = "html"
    elif format == "json":
        content = render_json_report(target, data)
        ext = "json"
    elif format == "markdown":
        content = render_markdown_report(
            target,
            data.get("subdomains"),
            data.get("ports"),
            data.get("http_checks")
        )
        ext = "md"
    else:
        raise ValueError(f"Unsupported format: {format}")
    
    filename = f"report_{target}_{now_iso().replace(':', '-')}.{ext}"
    filepath = os.path.join(output_dir, filename)
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    
    return filepath
